### ISSUE TITLE
RPM packages are built reproducible with SLE Micro 6.1

### ISSUE THREAD

**Issue by rsimai** [SUSE/release-notes#1]
Same as on Tumbleweed, RPM packages are built in a way to support reproducible builds in future, see https://reproducible-builds.org/. There is no change in how to handle RPM packages so users typically wouldn't notice. It however becomes visible when looking into the RPM metadata such as "Build Host" which is now unified, or "Build Date" which corresponds to the latest change in the package sources.

**Comment by KucharczykL** [comment]
Hi @rsimai, how does this impact the customer? If, like you said, the user wouldn't notice it's by definition not something we would usually put in the release notes.

**Comment by KucharczykL** [comment]
I have rephrased your original post like this, do you think that covers it?

```adoc
= Build Host and Build Date Metadata

The RPM packages that {productname} uses are built with reproducible builds in mind.
This is also reflected in the package metadata.
For example, the package's Build Date corresponds to the latest change in the package sources.
In contrast, regular packages's Build Date refers to the date when the package was built instead.
```

**Comment by rsimai** [comment]
Sure, if that's better understandable. Thanks.
